### ISSUE TITLE
Date evaluation

### ISSUE THREAD

**Issue by jcantonio** [PaesslerAG/gval#18]
Hello,

First your library looks great. Thank you for sharing.
I would like to evaluate  date + duration: 
date(myObject.date) + 3d
I was wondering what was the best approach: adding a new language?
Cheers,
JC

**Comment by generikvault** [comment]
Hi,

thanks :-)

You need the following operator and functions:

PostfixOperator("d", <int to duration>) // be aware that gval does not differentiate between "3d" and "3 d"
InfixOperator("+", <date,duration to date>)
Function("date", <string to date>)


If you need some of the default features use
 mylang := gval.Full(gval.Postfix(..), ...)
otherwise
 mylang := gval.NewLanguage(gval.Postfix(..), ...)

The defaul + is defined on string and int. So there shouldn't be any collisions.

Kind Regards,

GeneriK

**Comment by jcantonio** [comment]
Thanks GeneriK!
I will give a try tomorrow.

**Comment by jcantonio** [comment]
Hello,

I gave it a try.
With the code below, this expression works
`'date(foo.date) + 3d`
`
But it it not flexible.
It would be nicer if in the PostfixOperator I can pass the time.duration instead of a float64, so I I can extend to other PostfixOperators for hours, minutes and so on.
But I don't see how to use the PostfixOperator correctly:
- how to use the context to get the float value (if this is the way to get the float value)
- and then how to pass the new computed value (duration) to be used in the InfixOperator.
Cheers,

JClaude
```
	input := map[string]interface{}{
		"foo": map[string]interface{}{"date": `2014-01-01 23:59:59`},
	}
	langTimePlusDuration := gval.InfixOperator("+", func(a, b interface{}) (interface{}, error) {
		date, ok1 := a.(time.Time)
		days, ok2 := b.(float64)
		if ok1 && ok2 {
			newDate := date.Add(time.Hour * 24 * time.Duration(days))
			return newDate, nil
		}
		return nil, fmt.Errorf("unexpected operands types (%T) + (%T)", a, b)
	})

	langDuration := gval.PostfixOperator("d", func(c context.Context, p *gval.Parser, pre gval.Evaluable) (gval.Evaluable, error) {
		return func(c context.Context, v interface{}) (interface{}, error) {
			v, err := pre(c, v)
			if err != nil {
				return nil, err
			}
			return nil, nil
		}, nil
	})
	value, err := gval.Evaluate(`date(foo.date) + 3d`, input, langDuration, langTimePlusDuration)
	
```

**Comment by generikvault** [comment]
Hi,
the post operator is for converting the float to duration.
pre is the expression before the post operator. So this should do the job:
`func(c context.Context, v interface{}) (interface{}, error) {
			v, err := pre.EvalFloat64(c, v)
			if err != nil {
				return nil, err
			}
			return (24 * time.Hour.(float64) * v).(date.Duration), nil
}`
you can do the same for min, h and so on.

I'm a little confused that your code worked. The `return nil, nil` line looks a little bit of.

Cheers,

GeneriK

**Comment by jcantonio** [comment]
Thank you,

I am definitely missing something here.
With the code below, pre.EvalFloat64(c, v) gets evaluated before the conversion to the duration.
I expected the way around.

Thanks for your help.

JClaude

```
	input := map[string]interface{}{
		"foo": map[string]interface{}{"date": `2014-01-01 23:59:59`},
	}
	langTimePlusDuration := gval.InfixOperator("+", func(a, b interface{}) (interface{}, error) {
		date, ok1 := a.(time.Time)
		duration, ok2 := b.(time.Duration)
		if ok1 && ok2 {
			newDate := date.Add(duration)
			return newDate, nil
		}
		return nil, fmt.Errorf("unexpected operands types (%T) + (%T)", a, b)
	})

	langDuration := gval.PostfixOperator("d", func(c context.Context, p *gval.Parser, pre gval.Evaluable) (gval.Evaluable, error) {
		return func(c context.Context, v interface{}) (interface{}, error) {
			v, err := pre.EvalFloat64(c, v)
			if err != nil {
				return nil, err
			}
			return (time.Hour * 24 * time.Duration(int64(v.(float64)))), nil
		}, nil
	})
	value, err := gval.Evaluate(`date(foo.date) + 3d`, input, langDuration, langTimePlusDuration)
	if err != nil {
		fmt.Println(err)
	}

```

**Comment by generikvault** [comment]
Hi JClaude,

the Closure in the Postfix Operator is first executed. Variable `pre` referes to the expression before the post operator which is `3`. The first step of our post operator is to evaluate this expression and the second is to convert the result. In theory the operator could do stuff before calling `pre` (like modifying `v`) but in this case we need the result of `pre` in order to convert it. Thats why I choose this order of execution.

I hope this helps you :-)

**Comment by jcantonio** [comment]
It did help.
I just needed to add the Precedence and voilà!
Thank you for your time GeneriK.

**Comment by generikvault** [comment]
Oh yeah precedence is also a thing.
