### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by jcantonio** [PaesslerAG/gval#20]
Hello,
I was wondering what would be the way to handle keywords like: Now, Pi.
For now I add them as parameters in the Evaluate() function, but I was wondering if there was a more appropriate way to handle them.
Kind regards,
JClaude

**Comment by generikvault** [comment]
Hi JClaude,

you can use a Constant for Pi and a Function for Now. If you don't want to have the parentheses after now you could extend the gval lib with a `func KeyWord(s string, ext func(context.Context, *Parser) (Evaluable, error) Language)`. It's basicly like `PrefixExtension` but accept a literal/string instead of a rune.

Sorry for the slow answer. I got ill :-/

Kind regards,

Generik

**Comment by jcantonio** [comment]
Thank you Generik! Hope you get better :)
